### PR TITLE
Grammar changes

### PR DESCRIPTION
**Pull request by Randomno**
Addresses #68. I don't know if the WCT made any progress with this.

### CODE REVIEW

**Comment by campos20** [comment]
Thanks for this!

**Review by campos20 — APPROVED** [review]

**Comment by Randomno** [comment]
I don't know why the checks failed and if it's something to be concerned about. The only potential issue I could see is the `{" "}` ?

**Comment by campos20** [comment]
> I don't know why the checks failed and if it's something to be concerned about. The only potential issue I could see is the `{" "}` ?

We have prettier to check on that. You can run

```
cd client
yarn prettier_write
```

and commit

It is explained in the [README](https://github.com/thewca/statistics/blob/main/client/README.md#checkstyle)

I'll do that if you don't, you already helped us by fixing this. Thanks =]

**Comment by campos20** [comment]
Thanks @Randomno. I ran prettier, we are all set now.

**Pull request merged**
