### PR TITLE
Record evolution

### LINKED ISSUE #65: Create "evolution of records" graph
### Preliminary notes
* Links to [Issue 6742](https://github.com/thewca/worldcubeassociation.org/issues/6742) on WCA Website repo
* Please refer to [WCA Statistics 2.0 Transition Overview](https://docs.google.com/document/d/161YkIClOIl_YOwwr68v3VY_Nxkbo0RIKP9RiEFsvnfU/edit?usp=sharing) document for context around this change

## Requirement
One of the things still needed in the transition to Statistics 2.0 is an updated version of the ["Evolution of Records"](https://www.worldcubeassociation.org/results/misc/evolution/) graph. 

Basically, we need to recreate that graph in more modern frameworks (Python/ReactJS) inside this repo.

## Description of task

You will need to complete the following steps:
- [ ] A Python script to extract, generate and organise the source data for the graph 
- [ ] Create a frontend page to host the graph in ReactJS
- [ ] Integrate (ie, link to) the page from the main statistic.worldcubeassociation.org website. 
- [ ] Use research and judgement to decide how best to render the graph on the frontend - I don't know enough to advise on how to do this 

## General Comments

One person doesn't need to do all of this - if you only feel confident to do the Python or React sides of this, feel free to just do those.

Even if its one person doing everything, it is strongly recommended to submit a pull request for each piece of this, so that code review is easier. Please feel free to ask for help if you aren't sure if you're going in the right direction.

### PR DESCRIPTION
**Pull request by campos20**

### CODE REVIEW

**Comment by campos20** [comment]
Closes https://github.com/thewca/statistics/issues/65

**Comment by campos20** [comment]
https://user-images.githubusercontent.com/10170850/156949013-18102f48-6580-4946-8b59-a5e6f813a9ce.mp4

**Comment by dunkOnIT** [comment]
Looks incredible! To my eyes it looks spot-on - @gregorbg anything from your side?

**Comment by gregorbg** [comment]
Oh yes, this looks wonderful!

**Review by gregorbg — APPROVED** [review]
Thanks a lot Alexandre, LGTM :ship:

**Pull request merged**
